import { draftDarkTokens, themeFontStacks } from '../shared/themeTokens'
import type { DraftEditorTheme } from './editorThemeTypes'

export const draftDarkEditorTheme: DraftEditorTheme = {
  base: 'vs-dark',
  chromeVariables: {
    '--app-foreground': draftDarkTokens.foreground,
    '--draft-chrome-background': draftDarkTokens.chromeBackground,
    '--draft-divider-color': draftDarkTokens.divider,
    '--draft-muted-foreground': draftDarkTokens.muted,
    '--draft-pane-border': draftDarkTokens.borderSubtle,
    '--draft-subtle-foreground': draftDarkTokens.muted,
    '--editor-background': draftDarkTokens.editorBackground,
    '--editor-scrollbar-thumb': draftDarkTokens.scrollbarThumb,
    '--editor-scrollbar-track': 'transparent',
    '--editor-surface-background': draftDarkTokens.editorSurface,
    '--font-editor': themeFontStacks.editor,
    '--font-preview': themeFontStacks.preview,
    '--font-ui': themeFontStacks.ui,
    '--markdown-toolbar-background': draftDarkTokens.chromeBackground,
    '--markdown-toolbar-border': draftDarkTokens.border,
    '--markdown-toolbar-divider': '#242424',
    '--markdown-toolbar-foreground': '#acabaa',
    '--markdown-toolbar-hover-background': '#1f2020',
    '--markdown-toolbar-icon-filter': 'brightness(0) saturate(100%) invert(74%) sepia(6%) saturate(89%) hue-rotate(344deg) brightness(91%) contrast(88%)',
    '--markdown-toolbar-icon-primary-filter': 'brightness(0) saturate(100%) invert(78%) sepia(18%) saturate(720%) hue-rotate(184deg) brightness(105%) contrast(101%)',
    '--markdown-toolbar-muted': '#575757',
    '--markdown-toolbar-primary': draftDarkTokens.accentBlue,
    '--markdown-toolbar-radius': '10px',
    '--markdown-toolbar-selected-shortcut': 'rgba(165, 200, 255, 0.55)',
    '--markdown-toolbar-shadow': '0 18px 42px rgba(0, 0, 0, 0.44), 0 4px 12px rgba(0, 0, 0, 0.32)',
  },
  colors: {
    'editor.background': draftDarkTokens.chromeBackground,
    'editor.foreground': draftDarkTokens.foregroundBright,
    'editor.lineHighlightBackground': '#1a1a1a',
    'editor.lineHighlightBorder': draftDarkTokens.transparent,
    'editorCursor.foreground': '#A5C8FF',
    'editor.selectionBackground': '#214283AA',
    'editor.inactiveSelectionBackground': '#214283AA',
    'editor.selectionHighlightBackground': '#35353570',
    'editor.selectionHighlightBorder': draftDarkTokens.transparent,
    'editor.wordHighlightBackground': '#35353570',
    'editor.wordHighlightStrongBackground': '#FF880044',
    'editor.wordHighlightBorder': draftDarkTokens.transparent,
    'editor.wordHighlightStrongBorder': '#FF88FF',
    'editorLineNumber.foreground': '#504F4F',
    'editorLineNumber.activeForeground': '#A5C8FF',
    'editorIndentGuide.background': '#FF8800',
    'editorIndentGuide.activeBackground': '#FFD500',
    'editorWhitespace.foreground': draftDarkTokens.foregroundBright,
    'editorGutter.background': draftDarkTokens.chromeBackground,
    'editorOverviewRuler.border': '#FF0000',
  },
  currentLineDecorationBackground: '#1A1A1A',
  id: 'draftDark',
  inherit: true,
  label: 'Draft Dark',
  monacoThemeName: 'draft-dark',
  rules: [
    { token: 'comment', foreground: '504F4F' },
    { token: 'keyword', foreground: 'A5C8FF' },
    { token: 'keyword.heading.marker', foreground: 'A5C8FF' },
    { token: 'keyword.heading.text', foreground: 'A5C8FF' },
    { token: 'keyword.list.marker', foreground: '79A986' },
    { token: 'markup.quote.marker', foreground: 'F0BE6C' },
    { token: 'string', foreground: '79A986' },
    { token: 'number', foreground: 'FFD500' },
    { token: 'regexp', foreground: 'FF00FF' },
    { token: 'type', foreground: 'FF8800' },
    { token: 'delimiter', foreground: 'FF0000' },
    { token: 'delimiter.bracket', foreground: 'FF0000' },
  ],
}
